(import (poule) (scheme) (chicken base) (srfi-1))
(let* ((p (poule-create (cut expt 2 <>) 50))
       (j (list-tabulate 50 (cut poule-submit p <>)))
       (r (map (cut poule-result p <>) j)))
  (display r)
  (poule-destroy p))
